### ISSUE TITLE
Error returned by http client not processed early enough

### ISSUE THREAD

**Issue by Adrien-P** [gotsunami/mangopay2-go-sdk#4]
Hi,

On this line https://github.com/gotsunami/mangopay2-go-sdk/blob/master/service.go#L199 it is assumed that `resp != nil` which is not always the case. If 
`resp, err := DefaultClient.Do(req)` 
returns an error you can have resp == nil and then you'd get a panic (just happened to me):
`runtime error: invalid memory address or nil pointer dereference`

**Comment by aboutofpluto** [comment]
Hello Adrien! Thanks for you feedback.

Did you fix it and do you want to send us a pull request? If not, we will fix it soon.

**Comment by Adrien-P** [comment]
Pull request available here: https://github.com/gotsunami/mangopay2-go-sdk/pull/5

**Comment by aboutofpluto** [comment]
Merged.
